#!/bin/bash
#
# /etc/prompt-setup -or- $HOME/.prompt-setup
# This script customizes the PS1 and PS2 variables
# based on the current user and distro.
# Easily readable and consequently modifiable.
#
# Written by nootmuskaat

# determine distro
if [ -r /etc/os-release ]; then
    grep -qi 'centos' /etc/os-release && OS='centos'
    grep -qi 'red hat' /etc/os-release && OS='redhat'
    grep -qi 'suse' /etc/os-release && OS='suse'
    grep -qi 'ubuntu' /etc/os-release && OS='ubuntu'
    grep -qi 'debian' /etc/os-release && OS='debian'
    grep -qi 'arch' /etc/os-release && OS='arch'
    test -z "$OS" && OS='unknown'
else
    test -e /etc/centos-release && OS='centos'
    test -e /etc/redhat-release && OS='redhat'
    test -e /etc/SuSE-release && OS='suse'
    test -e /etc/ubuntu-release && OS='ubuntu'
    test -e /etc/debian_version && OS='debian'
    test -z "$OS" && OS='unknown'
fi

# formats
ROOT_PS1='\h:\w #'
ROOT_PS2='# >'
U='\u'
USER_PS1='@\h:\w \$'
USER_PS2='$ >'

END='\[\e[m\] '

# colors
RED='\[\e[31m\]'
GRN='\[\e[32m\]'
YLW='\[\e[33m\]'
BLU='\[\e[34m\]'
MAG='\[\e[35m\]'
CYN='\[\e[36m\]'
WHT='\[\e[37m\]'

BLK_ON_RED='\[\e[30;41m\]'
BLK_ON_GRN='\[\e[30;42m\]'
BLK_ON_YLW='\[\e[30;43m\]'
BLK_ON_BLU='\[\e[30;44m\]'
BLK_ON_MAG='\[\e[30;45m\]'
BLK_ON_CYN='\[\e[30;46m\]'
BLK_ON_WHT='\[\e[30;47m\]'

# The matching game
case "$OS" in 
    "centos") 
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_YLW$ROOT_PS1$END"
            export PS2="$BLK_ON_YLW$ROOT_PS2$END"
        else
            export PS1="$RED$U$YLW$USER_PS1$END" 
            export PS2="$YLW$USER_PS2$END" 
        fi;;
    "redhat") 
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_RED$ROOT_PS1$END"
            export PS2="$BLK_ON_RED$ROOT_PS2$END"
        else
            export PS1="$YLW$U$RED$USER_PS1$END" 
            export PS2="$RED$USER_PS2$END" 
        fi;;
    "suse") 
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_GRN$ROOT_PS1$END"
            export PS2="$BLK_ON_GRN$ROOT_PS2$END"
        else
            export PS1="$RED$U$GRN$USER_PS1$END" 
            export PS2="$GRN$USER_PS2$END" 
        fi;;
    "debian"|"ubuntu") 
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_MAG$ROOT_PS1$END"
            export PS2="$BLK_ON_MAG$ROOT_PS2$END"
        else
            export PS1="$YLW$U$MAG$USER_PS1$END" 
            export PS2="$MAG$USER_PS2$END" 
        fi;;
    "arch")
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_CYN$ROOT_PS1$END"
            export PS2="$BLK_ON_CYN$ROOT_PS2$END"
        else
            export PS1="$YLW$U$CYN$USER_PS1$END" 
            export PS2="$CYN$USER_PS2$END" 
        fi;;
    
    *) 
        if [ $UID -eq 0 ]; then
            export PS1="$BLK_ON_WHT$ROOT_PS1$END"
            export PS2="$BLK_ON_WHT$ROOT_PS2$END"
        else
            export PS1="$BLK_ON_WHT$U$USER_PS1$END" 
            export PS2="$BLK_ON_WHT$USER_PS2$END" 
        fi;;
esac
